FROM node:20-alpine AS builder

WORKDIR /app

COPY --chown=node:node package*.json ./
RUN npm ci

COPY . .

FROM node:20-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/src ./src
COPY --from=builder /app/knexfile.js ./knexfile.js

USER node

EXPOSE 3001

# Schema is created by Knex migrations inside npm start (knex.migrate.latest()).
CMD ["npm", "start"]
